# Generated by Django 3.2.9 on 2021-11-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/media/profilepic/default_profile.jpg', upload_to='profilepic/'),
        ),
    ]
