# Generated by Django 3.2.9 on 2021-11-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211115_0008'),
        ('accounts', '0004_profile_profile_pic'),
        ('accounts', '0006_alter_profile_image'),
    ]

    operations = [
    ]
